### ISSUE TITLE
Push to https?

### ISSUE THREAD

**Issue by siegesmund** [benoitc/erica#107]
Pushing erlang views via https results in the following error message: 

ERROR: push failed while processing ... : {'EXIT',
    {{badmatch,
         {error,
             {options,
                 {cacertfile,"/usr/local/bin/priv/ca-bundle.crt",
                     {error,enoent}}}}},
     [{erica_util,db_from_string,2,[{file,"src/erica_util.erl"},{line,74}]},
      {erica_push,push2,3,[{file,"src/erica_push.erl"},{line,51}]},
      {erica_push,push1,3,[{file,"src/erica_push.erl"},{line,44}]},
      {erica_core,run_modules,4,[{file,"src/erica_core.erl"},{line,98}]},
      {erica_core,execute,4,[{file,"src/erica_core.erl"},{line,68}]},
      {erica,main,1,[{file,"src/erica.erl"},{line,12}]},
      {escript,run,2,[{file,"escript.erl"},{line,752}]},
      {escript,start,1,[{file,"escript.erl"},{line,276}]}]}}

Not sure why this would be happening; wondering if it's a known issue?

**Comment by benoitc** [comment]
This issue is due to the latest change in hackney where the certificate is now validated. By default hackney is looking for the list of certificates in its `priv` directory. The certificate file is not shipped yet with erica which is the main issue there.

**Comment by siegesmund** [comment]
Is there a workaround in the short term?

**Comment by benoitc** [comment]
yes and it has been pushed in latest release:

https://github.com/benoitc/erica/commit/821c08a5fee286749e199d157ac2e817c511fa2c
