### ISSUE TITLE
Simple `erica push` giving `{badmatch,{error,conflict}` for no reason

### ISSUE THREAD

**Issue by fiatjaf** [benoitc/erica#97]
A simple ddoc push, with the same 0.4.0 erica version I've always used, even for this same design doc (actually, the problem happened with two ddocs I tried to upload to this same database, I didn't test in any other), gave me this error:

```
erica push ideas https://fiatjaf:password@fiatjaf.cloudant.com/ideacraft
==> ideacraft (push)
ERROR: push failed while processing /home/fiatjaf/ideacraft: {'EXIT',{{badmatch,{error,conflict}},
         [{erica_push,do_push,4},
          {erica_push,push2,3},
          {erica_push,push1,3},
          {erica_core,run_modules,4},
          {erica_core,execute,4},
          {erica,main,1},
          {escript,run,2},
          {escript,start,1}]}}
```

The views were written in coffeescript and compiled to javascript (with `--bare`). I tried the same command with and without a `.ericaignore` excluding the coffescript files.

Then I used the same command, just with `.ericaignore` renamed to `.couchappignore`, with the [couchapp](https://github.com/couchapp/couchapp) tool and it worked.

**Comment by benoitc** [comment]
i guess this have been solved in latest release via 29fc58e4138385bc886ecc13058a154df1d0763d . The pb above can't be related to the ignore file. Closing the issue then. Feel free to create a new one if it's till happening.
